#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.9"
# dependencies = ["python-pptx"]
# ///
"""Regression checks for docs/assets/sample_before.pptx / sample_after.pptx
(generated by gen-sample-pptx.mjs).

Consolidates the ad-hoc checks used to find and confirm two real bugs in the
generator: SmartArt parts with an invalid/missing content type (real
PowerPoint refused to open the file at all), and shapes positioned outside
the slide bounds (wrong assumed canvas size). python-pptx opening a file
without raising is NOT sufficient evidence either problem is absent -- see
docs/.scrolls/WISDOM.md -- so this checks content-types and shape geometry
directly instead of just trusting a clean open.

Run: uv run src/pptxdiff/test_gen-sample-pptx.py
(or: python3 src/pptxdiff/test_gen-sample-pptx.py, if python-pptx is already installed)
"""
import sys
from pathlib import Path

from pptx import Presentation
from pptx.opc.package import OpcPackage

ASSETS = Path(__file__).resolve().parent.parent.parent / "docs" / "assets"
FILES = {"before": ASSETS / "sample_before.pptx", "after": ASSETS / "sample_after.pptx"}
EXPECTED_SLIDE_COUNTS = {"before": 6, "after": 5}


def check_content_types(name, path):
    """Every part must have a real content type -- a generic 'application/xml'
    fallback means the writer never declared what the part actually is (the
    exact signal that caught the invalid SmartArt parts)."""
    pkg = OpcPackage.open(str(path))
    suspect = [str(part.partname) for part in pkg.iter_parts() if part.content_type == "application/xml"]
    assert not suspect, f"{name}: parts with generic/missing content type: {suspect}"
    for part in pkg.iter_parts():
        for rel in part.rels.values():
            if not rel.is_external:
                rel.target_part  # forces resolution; raises if the target is missing
    print(f"  [OK] {name}: content-types clean, all relationships resolve ({sum(1 for _ in pkg.iter_parts())} parts)")


def check_object_walk(name, prs):
    """Every shape/chart/table/notes object must be readable without exception."""
    for i, slide in enumerate(prs.slides):
        for shape in slide.shapes:
            shape.shape_type
            if shape.has_chart:
                for s in shape.chart.series:
                    list(s.values)
            if shape.has_table:
                for row in shape.table.rows:
                    for cell in row.cells:
                        cell.text
        if slide.has_notes_slide:
            slide.notes_slide.notes_text_frame.text
    print(f"  [OK] {name}: every shape/chart/table/notes object walks cleanly")


def check_bounds(name, prs):
    """No shape may extend past the slide's own declared width/height (the
    exact signal that caught the off-slide-elements bug)."""
    sw, sh = prs.slide_width, prs.slide_height
    out_of_bounds = []
    for i, slide in enumerate(prs.slides):
        for shape in slide.shapes:
            l, t, w, h = shape.left, shape.top, shape.width, shape.height
            if None in (l, t, w, h):
                continue
            if l < 0 or t < 0 or l + w > sw or t + h > sh:
                out_of_bounds.append(f"slide{i + 1}:{shape.name}")
    assert not out_of_bounds, f"{name}: shapes outside slide bounds: {out_of_bounds}"
    print(f"  [OK] {name}: no shapes outside slide bounds ({sw / 914400:.3f} x {sh / 914400:.3f} in)")


def check_slide_count(name, prs, expected):
    actual = len(prs.slides)
    assert actual == expected, f"{name}: expected {expected} slides, got {actual}"
    print(f"  [OK] {name}: slide count == {expected}")


def main():
    for name, path in FILES.items():
        assert path.exists(), f"{name}: missing file {path} -- run `node src/pptxdiff/gen-sample-pptx.mjs` first"
        print(f"=== {name} ({path.name}) ===")
        check_content_types(name, path)
        prs = Presentation(str(path))
        check_slide_count(name, prs, EXPECTED_SLIDE_COUNTS[name])
        check_object_walk(name, prs)
        check_bounds(name, prs)
    print("\nAll checks passed.")


if __name__ == "__main__":
    try:
        main()
    except AssertionError as e:
        print(f"\nFAIL: {e}", file=sys.stderr)
        sys.exit(1)
